<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="1" tests="4" name="MasterTest" time="47.849" errors="0" timestamp="2024-12-30T11:04:08 IST">
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="11.438">
    <skipped/>
  </testcase> <!-- validate_valid_user_credentials -->
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="10.757">
    <skipped/>
  </testcase> <!-- validate_valid_user_credentials -->
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="10.697">
    <skipped/>
  </testcase> <!-- validate_valid_user_credentials -->
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="10.708">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_ValidUserLoginTest.validate_valid_user_credentials(TC003_ValidUserLoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validate_valid_user_credentials -->
</testsuite> <!-- MasterTest -->
